Implemented: PDF generator(#1w3w78x)
hotwax/dxp-components pull request #10
Opened 2021-12-06 11:51 UTC by disha1202

![Screenshot from 2021-12-06 17-08-44](https://user-images.githubusercontent.com/58461801/144841214-4e439102-3398-4d5a-a834-78eda94b94fd.png)
![Screenshot from 2021-12-06 17-08-49](https://user-images.githubusercontent.com/58461801/144841230-f969b574-13c3-4223-b303-eefac4650011.png)

2021-12-09 06:59 UTC, disha1202 commented
![Screenshot from 2021-12-09 12-27-37](https://user-images.githubusercontent.com/58461801/145349058-86824e92-65c6-47ae-8a14-ef8c6430a0f6.png)

2021-12-10 10:29 UTC, ymaheshwari1 requested changes

2021-12-10 10:29 UTC, ymaheshwari1 commented on src/router/index.ts
> +  },
I think we can remove this.

2021-12-10 10:44 UTC, disha1202 commented on src/router/index.ts
> +  },
Sure sir

2021-12-15 07:17 UTC, ymaheshwari1 requested changes

2021-12-15 07:17 UTC, ymaheshwari1 commented on src/views/PdfGenerator.vue
> +   <PdfTemplate v-show="false" />
Improve Indentation

2021-12-15 07:17 UTC, ymaheshwari1 commented on src/views/PdfGenerator.vue
> +  components:{
```suggestion
  components: {
```

2021-12-15 07:17 UTC, ymaheshwari1 commented on src/views/PdfGenerator.vue
> +  methods:{
```suggestion
  methods: {
```

2021-12-15 07:17 UTC, ymaheshwari1 commented on src/views/PdfGenerator.vue
> +      const html =  htmlToPdfmake(pdfDocument.innerHTML);
Remove extra spaces

2022-01-06 09:54 UTC, ymaheshwari1 requested changes

2022-01-06 09:54 UTC, ymaheshwari1 commented on package.json
> -    "file-saver": "^2.0.5",
Revert this change.

2022-01-07 08:44 UTC, ymaheshwari1 approved these changes

2025-05-19 13:01 UTC, ymaheshwari1 commented
Closing as we do not have any requirement to generate the PDF from the app

2025-05-19 13:01 UTC, closed without merging