Implemented: menu footer navigation component (#126)
hotwax/dxp-components pull request #133
Opened 2023-09-06 09:24 UTC by sanskar345

### Steps to verify:
- check that this component works well with apps (like job manager)
- proper working of ion-select

### Description: 
- created user store having states that are being used in the footer navigation.

### Additional Info
- update pinia store state (user state) in login action by using useUserState which is being exported from dxp

2023-09-08 12:43 UTC, ymaheshwari1 requested changes

2023-09-08 12:43 UTC, ymaheshwari1 commented on src/components/MenuFooterNavigation.vue
> +        <ion-select interface="popover" :value="appUserState.currentShopifyConfig?.shopifyConfigId" @ionChange="$emit('changeShopifyConfig', $event)">
```suggestion
        <ion-select interface="popover" :value="appUserState.currentShopifyConfig?.shopifyConfigId" @ionChange="$emit('updateShopifyConfig', $event)">
```

2023-09-11 06:24 UTC, sanskar345 commented on src/components/MenuFooterNavigation.vue
> +        <ion-select interface="popover" :value="appUserState.currentShopifyConfig?.shopifyConfigId" @ionChange="$emit('changeShopifyConfig', $event)">
done

2023-09-21 13:11 UTC, k2maan requested changes

2023-09-21 13:11 UTC, k2maan commented on src/components/MenuFooterNavigation.vue
> +          <ion-select-option v-for="store in (appUserState.userProfile?.stores ? appUserState.userProfile.stores : [])" :key="store.productStoreId" :value="store.productStoreId">{{ store.storeName }}
```suggestion
          <ion-select-option v-for="store in appUserState.userProfile.stores" :key="store.productStoreId" :value="store.productStoreId">{{ store.storeName }}</ion-select-option>
```

2023-09-21 13:11 UTC, k2maan commented on src/components/MenuFooterNavigation.vue
> +const appUserState = computed(() => {
```suggestion
const userAppState = computed(() => {
```

2023-09-22 09:36 UTC, k2maan approved these changes

2023-10-10 13:16 UTC, ymaheshwari1 approved these changes

2023-10-10 13:21 UTC, merged