Implemented: centralized facility switcher to be used in all app (#138)
hotwax/dxp-components pull request #159
Opened 2023-09-14 05:39 UTC by amansinghbais

### Related Issues

Related Issue: #138

### Short Description and Why It's Useful

Implemented centralized facility switcher component of the settings app in dxp-components so that it can be used in any of the app.

### Steps to verify

- can verify the proper implementation of this using receiving app PR: https://github.com/hotwax/receiving/pull/264

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

2023-09-15 11:07 UTC, k2maan requested changes

2023-09-15 11:07 UTC, k2maan commented on src/components/FacilitySwitcher.vue
> +  const emit = defineEmits(['facility-change-alert', 'get-facility-details' ,'update-facility-id'])
Add info regarding the apps related to these events and a reference for defineEmits.

2023-09-15 11:07 UTC, k2maan commented on src/components/FacilitySwitcher.vue
> +  import { IonCard, IonCardContent, IonCardHeader, IonCardTitle, IonItem, IonLabel, IonSelect, IonSelectOption } from '@ionic/vue'
Remove tab spacing for all the code inside script.

2023-09-19 05:42 UTC, k2maan requested changes

2023-09-19 05:42 UTC, k2maan commented on src/components/FacilitySwitcher.vue
> +const store = appContext.config.globalProperties.$store;
```suggestion
const appState = appContext.config.globalProperties.$store;
```

2023-09-19 05:42 UTC, k2maan commented on src/components/FacilitySwitcher.vue
> +const appUserState = computed(() => {
```suggestion
const userAppState = computed(() => {
```

2023-09-19 05:42 UTC, k2maan commented on src/components/FacilitySwitcher.vue
> +  const currentAppUserState = appUserState.value
We should deep-clone the userAppState computed property to avoid side effects. Also, verify why are we using .value syntax.

2023-09-21 13:25 UTC, k2maan requested changes

2023-09-21 13:25 UTC, k2maan commented on src/components/FacilitySwitcher.vue
> +      {{ 'Specify which facility you want to operate from. Order, inventory and other configuration data will be specific to the facility you select.' }}
Internationalise all texts.

2023-10-03 06:45 UTC, ymaheshwari1 requested changes

2023-10-03 06:45 UTC, ymaheshwari1 commented on package-lock.json
> +}
Revert this change.

2023-10-03 06:45 UTC, ymaheshwari1 commented on src/components/FacilitySwitcher.vue
> +    if(appState.uploadProducts && Object.keys(appState.uploadProducts).length > 0 ) {
We should remove the app specific support from dxp.

2023-10-09 10:26 UTC, k2maan requested changes

2023-10-09 10:26 UTC, k2maan commented on src/components/FacilitySwitcher.vue
> +<template>
Rename the component to DxpFacilitySwticher

2023-10-10 09:07 UTC, k2maan requested changes

2023-10-10 09:07 UTC, k2maan commented on src/components/DxpFacilitySwitcher.vue
> +  if(currentUserAppState.currentFacility.facilityId && currentUserAppState.currentFacility.facilityId != selectedFacility && currentUserAppState.userProfile?.facilities) {
```suggestion
  if(currentUserAppState.currentFacility.facilityId !== selectedFacility && currentUserAppState.userProfile?.facilities) {
```

2023-10-10 09:08 UTC, k2maan requested changes

2023-10-10 09:08 UTC, k2maan commented on src/components/DxpFacilitySwitcher.vue
> +      'facility': currentUserAppState.userProfile.facilities.find((facility: any) => facility.facilityId == selectedFacility)
While implementing in apps, check if this is done in the actions already, and remove it if so.

2023-10-12 10:09 UTC, k2maan requested changes

2023-10-12 10:09 UTC, k2maan commented on src/components/DxpFacilitySwitcher.vue
> +    uploadProducts: appState.getters['product/getUploadProducts']
Not required now

2023-10-12 10:09 UTC, k2maan commented on src/components/DxpFacilitySwitcher.vue
> +});
Use arrow function syntax

2023-10-12 10:09 UTC, k2maan commented on src/components/DxpFacilitySwitcher.vue
> +  const selectedFacility = event.detail.value
```suggestion
  const facilityId = event.detail.value
```

2023-10-12 12:31 UTC, k2maan approved these changes

2024-11-06 05:36 UTC, ymaheshwari1 commented
Closing as handled in https://github.com/hotwax/dxp-components/pull/320

2024-11-06 05:36 UTC, closed without merging