Implemented: centralized facility selector with facilityId(#228)
hotwax/dxp-components pull request #320
Opened 2024-09-05 07:15 UTC by R-Sourabh

### Related Issues

#228 

### Short Description and Why It's Useful

- Created the `DxpFacilitySwitcher` component with a UI that displays an `ion-card` and `ion-modal` to select a facility.  
- The list of facilities now includes the `facilityId` as well.  
- Added a feature to select a facility using radio buttons and set it as the current facility.  
- Added actions to call OMS APIs to retrieve facilities, the preferred facility, and set the current facility.  
- Added getters to retrieve all facilities and the current facility.

### Screenshots of Visual Changes before/after (If There Are Any)

![Screenshot from 2024-09-05 12-36-07](https://github.com/user-attachments/assets/b93ee3f0-89d8-418a-a9ea-8ae508509517)
![Screenshot from 2024-09-05 12-35-50](https://github.com/user-attachments/assets/421ad0fe-19b3-44b5-8009-16ec60c5686b)

### Is the changes contains any breaking change?
If there are any breaking change include those in the release notes file

- [ ] Yes
- [x] No

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/dxp-components#contribution-guideline)

2024-10-10 06:12 UTC, ymaheshwari1 requested changes

2024-10-10 06:12 UTC, ymaheshwari1 commented on src/components/DxpFacilitySwitcher.vue
> +    facility.facilityName.toLowerCase().match(searchedString) ||
We should replace `match` with `includes`

2024-10-10 06:12 UTC, ymaheshwari1 commented on src/components/DxpFacilitySwitcher.vue
> +const findFacility = () => {
Add check before searching to check if the value is empty, also when matching the value trim the search string.

2024-10-10 06:12 UTC, ymaheshwari1 commented on src/components/DxpFacilitySwitcher.vue
> +  if(selectedFacility) {
I think we do not need this check here.

2024-10-16 06:04 UTC, ymaheshwari1 requested changes

2024-10-16 06:04 UTC, ymaheshwari1 commented on src/components/DxpFacilitySwitcher.vue
> +  if(searchedString) {
if we do not get searched string then display the default list again. Currently, if we have searched something and then there is no way to see the default list again as per this flow.

2024-10-16 07:15 UTC, ymaheshwari1 requested changes

2024-10-16 07:15 UTC, ymaheshwari1 commented on src/components/DxpFacilitySwitcher.vue
> +  if(isUpdated) {
We should not wait for whether the preference for user is set or not, instead we should allow the user to update the facility in the app, irrespective of preference set on the server.

2024-10-16 07:15 UTC, ymaheshwari1 commented on src/store/user.ts
> +    async setFacility(payload: any) {
setFacilityPreference

2024-10-16 07:15 UTC, ymaheshwari1 commented on src/components/DxpFacilitySwitcher.vue
> +function setFacility() {
```suggestion
function updateFacility() {
```

2024-10-16 13:22 UTC, ymaheshwari1 commented on src/store/user.ts
> +        preferredFacilityId = await facilityContext.getUserPreference(authStore.getToken.value, authStore.getBaseUrl, userPrefTypeId);
```suggestion
        let preferredFacilityId = await facilityContext.getUserPreference(authStore.getToken.value, authStore.getBaseUrl, userPrefTypeId);
```

2024-10-16 13:22 UTC, ymaheshwari1 commented on src/store/user.ts
> +      preferredFacility = this.facilities[0];
```suggestion
      if (!this.facilities.length) {
        return;
      }
      let preferredFacility = this.facilities[0];
```

2024-10-16 13:23 UTC, ymaheshwari1 commented on src/store/user.ts
> +    async getPreferredFacility(userPrefTypeId: any) {
```suggestion
    async getFacilityPreference(userPrefTypeId: any) {
```

2024-10-16 13:25 UTC, ymaheshwari1 commented on src/components/DxpFacilitySwitcher.vue
> +  emit('updateFacility', selectedFacility.facilityId);
```suggestion
  emit('updateFacility', selectedFacility);
```

2024-10-17 05:04 UTC, ymaheshwari1 approved these changes

2024-10-17 05:04 UTC, merged

2025-01-01 22:54 UTC, dt2patel reviewed
Missed feature in implementation

2025-01-01 22:54 UTC, dt2patel commented on src/components/DxpFacilitySwitcher.vue
> +      <ion-button id="open-facility-modal" slot="end" fill="outline" color="dark">{{ $t('Change')}}</ion-button>
this button should only be shown if the user is associated with more than one facility. @R-Sourabh 

<img width="615" alt="Screenshot 2025-01-01 at 5 54 07 PM" src="https://github.com/user-attachments/assets/f56f243a-3bf2-4834-ba9c-1312f433b66b" />